services:
  portal-service:
    container_name: portal-service
    build: .
    env_file:
      - /home/deploy/config/.env.common
      - .env.staging
    ports:
      - "4001:4001"
    restart: always
    networks:
      - gateway_app-net

networks:
  gateway_app-net:
    external: true
