services:
  portal-service:
    container_name: portal-service
    build: .
    env_file:
      - /home/deploy/config/.env.common
      - .env.staging
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4001/health"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    ports:
      - "4001:4001"
    restart: always
    networks:
      - gateway_app-net

networks:
  gateway_app-net:
    external: true
