version: "3.9"

services:
  portal-service:
    container_name: portal-service
    build: .
    ports:
      - "4001:4001"
    restart: always
    networks:
      - gateway_app-net

networks:
  gateway_app-net:
    external: true
